version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  app:
    depends_on:
      - "db"
    build: .
    env_file:
      - ormconfig.env
      - .env
    ports:
      - "8080:8080"