name: Node Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main
      - name: Setup enviroment
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Instal node
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build    